version: "3"
services:
  install:
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
  installTest:
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app/test && rm -rf node_modules && rm -f package-lock.json && npm run cp:libs && npm i"
  build: 
    user: node
    image: node:18
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"  
  serve:
    user: node
    image: node:18
    ports:
      - "8099:8099"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run serve"   
  test:
    user: node
    image: node:18
    ports:
      - "8099:8099"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run test"       
  dev:
    #docker-compose run --rm dev bash
    user: node
    image: node:18
    working_dir: /data
    volumes:
      - .:/data
    tty: true
    stdin_open: true